FROM docker.io/nginx:1.17.0-alpine
EXPOSE 80
VOLUME ["/etc/nginx/conf.d","/etc/nginx/certs","/usr/share/nginx/html"]
COPY index.html.v1.0 /usr/share/nginx/html/index.html
CMD ["nginx", "-g", "daemon off;"]
