all:
  children:
    echo:
      vars:
        container_registry: localhost:5000
        port_prefix: 16
      children:
        echo_kbus:
          vars:
            kbus_image_version: v1.1
            kbus_image_name: kbus_base
          hosts:
            localhost:
              ansible_connection: local
